In [19]:
import pandas  as pd

In [21]:
with open("WhatsApp Chat with Kirthi.txt", "r", encoding="utf-8") as file:
    chat = file.readlines()

In [23]:
df = pd.DataFrame(chat, columns=["Chat"])

In [25]:
df

                                                  Chat
0    1/26/24, 12:16 PM - Messages and calls are end...
1          10/14/26, 1:47 PM - Nivetha: Good morning\n
2          10/14/26, 1:47 PM - Nivetha: How are you?\n
3                     10/14/26, 1:49 PM - Kirthi: Hi\n
4               10/14/26, 1:50 PM - Kirthi: Good..u?\n
..                                                 ...
145  10/19/26, 12:45 PM - Kirthi: Sure, come over a...
146  10/19/26, 12:45 PM - Nivetha: Wow, such hospit...
147  10/19/26, 12:46 PM - Kirthi: May be you do. I'...
148  10/19/26, 12:46 PM - Nivetha: I'll remember th...
149  10/19/26, 12:47 PM - Kirthi: Okay, talk later....

[150 rows x 1 columns]

In [27]:
Date=df["Chat"].str.split(",",n=1,expand=True)
Date

            0                                                  1
0     1/26/24   12:16 PM - Messages and calls are end-to-end ...
1    10/14/26                  1:47 PM - Nivetha: Good morning\n
2    10/14/26                  1:47 PM - Nivetha: How are you?\n
3    10/14/26                             1:49 PM - Kirthi: Hi\n
4    10/14/26                       1:50 PM - Kirthi: Good..u?\n
..        ...                                                ...
145  10/19/26   12:45 PM - Kirthi: Sure, come over and I'll g...
146  10/19/26   12:45 PM - Nivetha: Wow, such hospitality! I ...
147  10/19/26   12:46 PM - Kirthi: May be you do. I'll consid...
148  10/19/26   12:46 PM - Nivetha: I'll remember that. Anywa...
149  10/19/26   12:47 PM - Kirthi: Okay, talk later. Don't mi...

[150 rows x 2 columns]

In [29]:
Time=Date[1].str.split("-",n=1,expand=True)
Time

              0                                                  1
0     12:16 PM    Messages and calls are end-to-end encrypted. ...
1      1:47 PM                             Nivetha: Good morning\n
2      1:47 PM                             Nivetha: How are you?\n
3      1:49 PM                                        Kirthi: Hi\n
4      1:50 PM                                  Kirthi: Good..u?\n
..          ...                                                ...
145   12:45 PM    Kirthi: Sure, come over and I'll give you an ...
146   12:45 PM    Nivetha: Wow, such hospitality! I deserve bet...
147   12:46 PM          Kirthi: May be you do. I'll consider it😜\n
148   12:46 PM    Nivetha: I'll remember that. Anyway, I need t...
149   12:47 PM    Kirthi: Okay, talk later. Don't miss me too m...

[150 rows x 2 columns]

In [31]:
Name=Time[1].str.split(":",n=1,expand=True)
Name

,0,1
0,Messages and calls are end-to-end encrypted. ...,None
1,Nivetha,Good morning\n
2,Nivetha,How are you?\n
3,Kirthi,Hi\n
4,Kirthi,Good..u?\n
...,...,...
145,Kirthi,"Sure, come over and I'll give you an empty bo..."
146,Nivetha,"Wow, such hospitality! I deserve better from ..."
147,Kirthi,May be you do. I'll consider it😜\n
148,Nivetha,"I'll remember that. Anyway, I need to get bac..."
149,Kirthi,"Okay, talk later. Don't miss me too much😂\n"

In [33]:
df=df.drop(0)

In [35]:
df["Date"]=Date[0]
df["Time"]=Time[0]
df["Name"]=Name[0]
df["Chat"]=Name[1]

In [37]:
df=df[["Date","Time","Name","Chat"]]

In [39]:
df["Chat"] = df["Chat"].str.strip()

In [41]:
df

,Date,Time,Name,Chat
1,10/14/26,1:47 PM,Nivetha,Good morning
2,10/14/26,1:47 PM,Nivetha,How are you?
3,10/14/26,1:49 PM,Kirthi,Hi
4,10/14/26,1:50 PM,Kirthi,Good..u?
5,10/14/26,1:50 PM,Nivetha,Fine😊
...,...,...,...,...
145,10/19/26,12:45 PM,Kirthi,"Sure, come over and I'll give you an empty bowl😂"
146,10/19/26,12:45 PM,Nivetha,"Wow, such hospitality! I deserve better from you."
147,10/19/26,12:46 PM,Kirthi,May be you do. I'll consider it😜
148,10/19/26,12:46 PM,Nivetha,"I'll remember that. Anyway, I need to get back..."
149,10/19/26,12:47 PM,Kirthi,"Okay, talk later. Don't miss me too much😂"

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149 entries, 1 to 149
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    149 non-null    object
 1   Time    149 non-null    object
 2   Name    149 non-null    object
 3   Chat    149 non-null    object
dtypes: object(4)
memory usage: 4.8+ KB

In [45]:
df.isnull().sum()

Date    0
Time    0
Name    0
Chat    0
dtype: int64

In [47]:
#%pip install openpyxl

In [49]:
#df.to_excel("whatsapp_chat.xlsx", index=False)

In [51]:
dataset=pd.read_csv("whatsapp_chat_labeled.csv")
dataset

,Date,Time,Name,Chat,Label
0,10/14/26,1:47 PM,Nivetha,Good morning,Normal
1,10/14/26,1:47 PM,Nivetha,How are you?,Normal
2,10/14/26,1:49 PM,Kirthi,Hi,Normal
3,10/14/26,1:50 PM,Kirthi,Good..u?,Normal
4,10/14/26,1:50 PM,Nivetha,Fine😊,Normal
...,...,...,...,...,...
144,10/19/26,12:45 PM,Kirthi,"Sure, come over and I'll give you an empty bowl😂",Normal
145,10/19/26,12:45 PM,Nivetha,"Wow, such hospitality! I deserve better from you.",Flirty
146,10/19/26,12:46 PM,Kirthi,May be you do. I'll consider it😜,Flirty
147,10/19/26,12:46 PM,Nivetha,"I'll remember that. Anyway, I need to get back...",Normal
148,10/19/26,12:47 PM,Kirthi,"Okay, talk later. Don't miss me too much😂",Flirty

In [55]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149 entries, 0 to 148
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    149 non-null    object
 1   Time    149 non-null    object
 2   Name    149 non-null    object
 3   Chat    149 non-null    object
 4   Label   149 non-null    object
dtypes: object(5)
memory usage: 5.9+ KB

In [59]:
data=dataset

In [61]:
 def sentimentalAnalysis(data,columnname):
        from nltk.sentiment.vader import SentimentIntensityAnalyzer
        sid = SentimentIntensityAnalyzer()
        
        #Deleting null pr empty value
        data.dropna(inplace=True)
        
        #Creating respective columns
        
        data['scores'] = data[columnname].apply(lambda commentText: sid.polarity_scores(commentText))
        data['compound']  = data['scores'].apply(lambda score_dict: score_dict['compound'])
        data['Negtive']  = data['scores'].apply(lambda score_dict: score_dict['neg'])
        data['Postive']  = data['scores'].apply(lambda score_dict: score_dict['pos'])
        data['Neutral']  = data['scores'].apply(lambda score_dict: score_dict['neu'])
        
        #Creating final pos or neg using compound score
        data['comp_score'] = data['compound'].apply(lambda c: 'pos' if c >=0 else 'neg')
       
        #Checking how many pos and neg
        posneg=pd.DataFrame(data['comp_score'].value_counts())
        return posneg,data

In [63]:
pos,data_Senti=sentimentalAnalysis(data,columnname='Chat')

In [65]:
pos

            count
comp_score
pos           139
neg            10

In [67]:
data_Senti

,Date,Time,Name,Chat,Label,scores,compound,Negtive,Postive,Neutral,comp_score
0,10/14/26,1:47 PM,Nivetha,Good morning,Normal,"{'neg': 0.0, 'neu': 0.256, 'pos': 0.744, 'comp...",0.4404,0.000,0.744,0.256,pos
1,10/14/26,1:47 PM,Nivetha,How are you?,Normal,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
2,10/14/26,1:49 PM,Kirthi,Hi,Normal,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
3,10/14/26,1:50 PM,Kirthi,Good..u?,Normal,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
4,10/14/26,1:50 PM,Nivetha,Fine😊,Normal,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
...,...,...,...,...,...,...,...,...,...,...,...
144,10/19/26,12:45 PM,Kirthi,"Sure, come over and I'll give you an empty bowl😂",Normal,"{'neg': 0.149, 'neu': 0.661, 'pos': 0.19, 'com...",0.1280,0.149,0.190,0.661,pos
145,10/19/26,12:45 PM,Nivetha,"Wow, such hospitality! I deserve better from you.",Flirty,"{'neg': 0.0, 'neu': 0.417, 'pos': 0.583, 'comp...",0.7901,0.000,0.583,0.417,pos
146,10/19/26,12:46 PM,Kirthi,May be you do. I'll consider it😜,Flirty,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
147,10/19/26,12:46 PM,Nivetha,"I'll remember that. Anyway, I need to get back...",Normal,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
148,10/19/26,12:47 PM,Kirthi,"Okay, talk later. Don't miss me too much😂",Flirty,"{'neg': 0.0, 'neu': 0.642, 'pos': 0.358, 'comp...",0.3278,0.000,0.358,0.642,pos

In [69]:
#Building models

In [155]:
import pandas as pd
import numpy as np
import itertools
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, HashingVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.naive_bayes import MultinomialNB,GaussianNB,ComplementNB,BernoulliNB,CategoricalNB
from sklearn.svm import SVC
from sklearn import metrics
import matplotlib.pyplot as plt

In [83]:
x=dataset["Chat"]
y=dataset["Label"]

In [89]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=53)

In [95]:
count_vectorizer = CountVectorizer(stop_words='english')
count_train = count_vectorizer.fit_transform(X_train)
count_test = count_vectorizer.transform(X_test)

In [97]:
len(count_vectorizer.get_feature_names_out())#unique words

155

In [99]:
print(count_train.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]
 ...
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]]

In [101]:
clf = MultinomialNB()
clf.fit(count_train, y_train)
pred = clf.predict(count_test)
score = metrics.accuracy_score(y_test, pred)
print("accuracy:   %0.3f" % score)
cm = metrics.confusion_matrix(y_test, pred)

accuracy:   0.560

In [105]:
from sklearn.metrics import classification_report
report=classification_report(y_test, pred)
print(report)

              precision    recall  f1-score   support

      Flirty       0.72      0.43      0.54        30
      Normal       0.47      0.75      0.58        20

    accuracy                           0.56        50
   macro avg       0.60      0.59      0.56        50
weighted avg       0.62      0.56      0.56        50

In [127]:
clf = GaussianNB()
count_array_train=count_train.toarray()
count_array_test=count_test.toarray()
clf.fit(count_array_train, y_train)
pred = clf.predict(count_array_test)
score = metrics.accuracy_score(y_test, pred)
print("accuracy:   %0.3f" % score)
cm = metrics.confusion_matrix(y_test, pred)

accuracy:   0.560

In [129]:
from sklearn.metrics import classification_report
report=classification_report(y_test, pred)
print(report)

              precision    recall  f1-score   support

      Flirty       0.61      0.73      0.67        30
      Normal       0.43      0.30      0.35        20

    accuracy                           0.56        50
   macro avg       0.52      0.52      0.51        50
weighted avg       0.54      0.56      0.54        50

In [137]:
clf = ComplementNB()
clf.fit(count_train, y_train)
pred = clf.predict(count_test)
score = metrics.accuracy_score(y_test, pred)
print("accuracy:   %0.3f" % score)
cm = metrics.confusion_matrix(y_test, pred)

accuracy:   0.500

In [139]:
from sklearn.metrics import classification_report
report=classification_report(y_test, pred)
print(report)

              precision    recall  f1-score   support

      Flirty       0.58      0.60      0.59        30
      Normal       0.37      0.35      0.36        20

    accuracy                           0.50        50
   macro avg       0.47      0.47      0.47        50
weighted avg       0.50      0.50      0.50        50

In [143]:
clf = BernoulliNB()
clf.fit(count_train, y_train)
pred = clf.predict(count_test)
score = metrics.accuracy_score(y_test, pred)
print("accuracy:   %0.3f" % score)
cm = metrics.confusion_matrix(y_test, pred)

accuracy:   0.500

In [145]:
from sklearn.metrics import classification_report
report=classification_report(y_test, pred)
print(report)

              precision    recall  f1-score   support

      Flirty       0.78      0.23      0.36        30
      Normal       0.44      0.90      0.59        20

    accuracy                           0.50        50
   macro avg       0.61      0.57      0.47        50
weighted avg       0.64      0.50      0.45        50

In [151]:
clf = CategoricalNB()
count_array_train=count_train.toarray()
count_array_test=count_test.toarray()
clf.fit(count_array_train, y_train)
pred = clf.predict(count_array_test)
score = metrics.accuracy_score(y_test, pred)
print("accuracy:   %0.3f" % score)
cm = metrics.confusion_matrix(y_test, pred)

accuracy:   0.500

In [153]:
from sklearn.metrics import classification_report
report=classification_report(y_test, pred)
print(report)

              precision    recall  f1-score   support

      Flirty       0.78      0.23      0.36        30
      Normal       0.44      0.90      0.59        20

    accuracy                           0.50        50
   macro avg       0.61      0.57      0.47        50
weighted avg       0.64      0.50      0.45        50

In [197]:
clf = SVC(kernel='linear')
clf.fit(count_train, y_train)
pred = clf.predict(count_test)
score = metrics.accuracy_score(y_test, pred)
print("accuracy:   %0.3f" % score)
cm = metrics.confusion_matrix(y_test, pred)

accuracy:   0.520

In [199]:
from sklearn.metrics import classification_report
report=classification_report(y_test, pred)
print(report)

              precision    recall  f1-score   support

      Flirty       0.69      0.37      0.48        30
      Normal       0.44      0.75      0.56        20

    accuracy                           0.52        50
   macro avg       0.56      0.56      0.52        50
weighted avg       0.59      0.52      0.51        50